services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  users:
    build: ./backend/users
    environment:
      - dbURL=${dbURL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
    ports:
      - "5001:5001"

  books:
    build: ./backend/books
    environment:
      - dbURL=${dbURL}
    depends_on:
      - db
    ports:
      - "5002:5002"

volumes:
  mysql_data:
