networks:
  public_net:
  internal_net:

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:3000"
  #   networks:
  #     - public_net
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - internal_net

  users:
    build: ./backend/users
    restart: always
    environment:
      - dbURL=${dbURL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
    ports:
      - "5001:5001"
    networks:
      - public_net
      - internal_net

  books:
    build: ./backend/books
    restart: always
    environment:
      - dbURL=${dbURL}
    depends_on:
      - db
    ports:
      - "5002:5002"
    networks:
      - public_net
      - internal_net

  orders:
    build: ./backend/orders
    restart: always
    environment:
      - dbURL=${dbURL}
    depends_on:
      - db
      - users
      - books
    # ports:
    #   - "5003:5003" # remove later
    networks:
      - internal_net

  rabbitmq:
    image: rabbitmq:4-management
    restart: always
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PW}
    networks:
      - internal_net

  placeorder:
    build:
      context: ./backend
      dockerfile: place_order/Dockerfile
    restart: always
    environment:
      - dbURL=${dbURL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PW}
    depends_on:
      - db
      - users
      - books
      - orders
      - rabbitmq
    ports:
      - "5004:5004"
    networks:
      - public_net
      - internal_net

  orderprocessing:
    build:
      context: ./backend
      dockerfile: order_processing/Dockerfile
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PW}
    depends_on:
      - db
      - users
      - books
      - orders
      - rabbitmq
    networks:
      - internal_net

  displayorders:
    build: 
      context: ./backend
      dockerfile: display_orders/Dockerfile
    restart: always
    environment:
      - dbURL=${dbURL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - db
      - users
      - books
      - orders
    ports:
      - "5005:5005"
    networks:
      - public_net
      - internal_net

volumes:
  mysql_data:
