# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend (Node.js) CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        run: npm ci

      # Lint once on Node 20.x
      - name: Lint (ESLint)
        if: ${{ matrix.node-version == '20.x' }}
        run: |
          npm run lint --if-present || npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings=0
      
      - name: Typecheck (TS)
        if: ${{ matrix.node-version == '20.x' }}
        run: npm run typecheck

      - name: Build
        run: npm run build --if-present
        env:
          CI: true
