name: Release

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure .env exists
        run: cp -n .env.example .env || true

      - name: Build images (pull newer base layers)
        run: |
          set -euo pipefail
          docker compose build --pull

      - name: Bring stack up
        run: docker compose up -d --remove-orphans

      - name: Show status
        run: docker compose ps

      - name: Tail last logs on failure
        if: failure()
        run: docker compose logs --no-color --tail=100